config/routes.rb
OpenExam::Application.routes.draw do
  
  get "homepage/index"

  get '', to: 'quizzes#index', constraints: lambda {|r| r.subdomain.present? && r.subdomain != 'www'}

  get "about", to: 'info#about'
  get "privacy", to: 'info#privacy', as: 'privacy'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/quiz/:quiz_id' => 'admin#quiz', as: 'quiz_stats'

  get "sessions/new"

  get 'quizzes/:id/score/:user_id' => 'quizzes#score', as: 'score'

  get 'quizzes/:id/invite' => 'quizzes#invite', as: 'quiz_invite'
  post 'quizzes/mail_invite' => 'quizzes#mail_invite'
  
  get 'quizzes/collaborate' => 'quizzes#collaborate', as: 'quiz_collaborate'

  get 'users/invite' => 'users#invite', as: 'invite_users'
  post 'users/create_students' => 'users#create_students'

  get 'organizations/demo' => 'organizations#demo'

  resources :organizations

  resources :quizzes

  resources :users

  resources :sessions

  resources :questions do
    resources :answers, :controller => 'questions/answers'
  end

  root :to => 'homepage#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  # GET /quizzes
  # GET /quizzes.json
  before_filter :authorize, only: [:edit, :show, :update, :new, :destroy, :index, :collaborate, :history]
  before_filter :authorize_admin, only: [:edit, :new, :destroy, :update, :create, :invite, :mail_invite]
  before_filter :organizations_only

  def index
    @ready_quizzes = current_org.quizzes.select(&:is_ready_to_take?)
    @quizzes_to_take = @ready_quizzes.select{|quiz| !current_user.has_taken?(quiz) && !current_user.has_started?(quiz)}
    @quizzes_to_resume = @ready_quizzes.select{|quiz| !current_user.has_taken?(quiz) && current_user.has_started?(quiz)}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quizzes }
    end
  end

  def collaborate
    @quizzes = current_org.quizzes.where(:is_published => false)

    respond_to do |format|
      format.html
      format.json { render json: @quizzes }
    end
  end

  def invite
    @quiz = current_org.quizzes.find(params[:id])
    @users = User.all.select{|user| !user.is_admin?}
  end

  def mail_invite
    quiz_id = params.fetch(:quiz_id).to_i
    quiz = current_org.quizzes.find(quiz_id)
    OpenExamMailer.collaboration_invite(params.fetch(:recipients), quiz).deliver
    respond_to do |format|
      format.html { redirect_to quiz_collaborate_path }
    end
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @quiz = current_org.quizzes.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/new
  # GET /quizzes/new.json
  def new
    @quiz = Quiz.new(:organization_id => current_org.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/1/edit
  def edit
    @quiz = current_org.quizzes.find(params[:id])
    @quiz.questions.build if @quiz.questions.empty?
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(params[:quiz])

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, :flash => { :success => "Quiz was successfully created." } }
        format.json { render json: @quiz, status: :created, location: @quiz }
      else
        format.html { render action: "new" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quizzes/1
  # PUT /quizzes/1.json
  def update
    @quiz = current_org.quizzes.find(params[:id])

    if @quiz.publish(params[:quiz][:is_published])
    else
      @quiz.errors.add :base, "Quiz must have one selected question to publish."
    end

    respond_to do |format|

      if @quiz.update_attributes(params[:quiz].except(:is_published))
        format.html { redirect_to @quiz }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz = current_org.quizzes.find_by_id(params[:id])
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url }
      format.json { head :no_content }
    end
  end

  def score
    @user = User.find_by_id(params[:user_id])

    respond_to do |format|
      if @user == current_user || current_user.is_admin?
        @quiz = current_org.quizzes.find_by_id(params[:id])
        @user_quiz = UserQuiz.find_by_user_id_and_quiz_id(@user.id, @quiz.id)
        @answers = @user.answers_for_quiz(@quiz.id)
        format.html
      elsif current_user.id != @user.id
        format.html { redirect_to privacy_path, :alert => "Stop trying to hack this shit" }
      else  
        format.html { redirect_to quizzes_path, :notice => "You haven't taken this quiz yet." }
      end
    end

    
  end

  
end

app/helpers/quizzes_helper.rb
module QuizzesHelper

end

app/views/quizzes/_form.html.erb
  <%= form_for(@quiz) do |f| %>
    <% if @quiz.errors.any? %>
      <div id="error_explanation" class="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h4><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h4>

        <ul>
        <% @quiz.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :organization_id %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'input-xxlarge' %>
    </div>

   <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, :class => 'input-xxlarge', :rows => 5 %>
   </div>


  <div class="field">
      <%= f.label :passing_grade %>
      <%= f.text_field :passing_grade, :placeholder => "Must be between 0 and 100" %>
   </div>


    <div class="actions">
          <button class="btn btn-primary" name="commit" type="submit" value="Create Quiz">Create Quiz</button>
    </div>
  <% end %>

app/views/quizzes/_question_fields.html.erb
<fieldset>
  <%= f.label :name, "Question" %> <br />
  <%= f.text_area :name %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <%= f.fields_for :choices do |builder| %>
    <%= render 'choice_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Choice", f, :choices %>
</fieldset>  

app/views/quizzes/collaborate.html.erb
<%if current_user.is_admin? %>
  <div class="well">
  <div class="btn-group">
    <%= link_to 'Create a Quiz', new_quiz_path, :class => "btn btn-success" %>
  </div>
  </div>
<% end %>

<div class="row"> <div class="span10 offset1">
    <div class="quiz-content">
      <div class="quiz-header">
        <h2>Add a Question</h2>
      </div>
      <div class="quiz-list">
        <ul>
        <% @quizzes.each do |quiz| %>
          <li>
            <a href="<%= quiz_path(quiz) %>">
              <span class="title"><%= truncate(quiz.name, :length => 30) %></span>
              <span class="description">(<%= quiz.questions.length %> submitted, <%= quiz.approved_questions.length %> approved) <%= truncate(quiz.description, :length => 30) %></span>              
            </a>
            <span class="links">
              <% if current_user.is_admin? %>
                <%= link_to 'Edit', edit_quiz_path(quiz), :class => "edit-icon" %>
                <%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' }, :class => "trash-icon" %>
              <% end %>
            </span>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
</div> </div>

  <script type="text/javascript">
  $(function(){
    $('.edit-icon').tooltip({
      title: "Edit quiz"
    });
    $('.trash-icon').tooltip({
      title: "Delete quiz"
    });
  });
</script>

app/views/quizzes/edit.html.erb
<div class="row"> <div class="span10 offset1">
<h1>Editing <%= @quiz.name%></h1>

<%= render 'form' %>

<%= link_to 'Show quiz', @quiz %> |
<%= link_to 'Back', quizzes_path %>
</div> </div>

app/views/quizzes/index.html.erb
<div class="row"> <div class="span10 offset1">
<div class="quiz-content">
  <% if !@quizzes_to_take.empty? %>
    <div class="quiz-header">
      <h2>Take a Quiz</h2>
    </div>
    <div class="quiz-list">
      <ul>
      <% @quizzes_to_take.each do |quiz| %>
          <li>
            <a href="<%= new_question_answer_path(quiz.approved_questions.first) %>">
              <span class="title"><%= truncate(quiz.name, :length => 30) %></span>
              <span class="description"> (<%= pluralize(quiz.approved_questions.length, 'question') %>)  <%= truncate(quiz.description, :length => 30) %></span>
            </a>
            <span class="links">
              <% if current_user.is_admin? %>
                <%= link_to 'Edit', edit_quiz_path(quiz), :class => "edit-icon"  %>
                <%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' }, :class => "trash-icon" %>
              <% end %>
            </span>
          </li>
      <% end %>        
      </ul>
    </div>
  <% elsif @quizzes_to_take.empty? &&  @quizzes_to_resume.empty? %>
    <h2>No new quizzes to take</h2>
  <% end %>

  <% if !@quizzes_to_resume.empty? %>
    <h2>Resume Quiz</h2>
    <div class="quiz-list">
      <ul>
      <% @quizzes_to_resume.each do |quiz| %>
          <li>
            <a href="<%= new_question_answer_path(quiz.question_to_resume(current_user)) %>"
              <span class="title"><%= truncate(quiz.name, :length => 30) %></span>
              <span class="description">(<%= pluralize(quiz.approved_questions.length, 'question') %>) <%= truncate(quiz.description, :length => 30) %></span>
            </a>
            <span class="links">
              <% if current_user.is_admin? %>
                <%= link_to 'Edit', edit_quiz_path(quiz), :class => "edit-icon"  %>
                <%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' }, :class => "trash-icon" %>
              <% end %>
            </span>
          </li>
      <% end %>        
      </ul>
    </div>
  <% end %>
</div>

</div> </div>

<script type="text/javascript">
  $(function(){
    $('.edit-icon').tooltip({
      title: "Edit quiz"
    });
    $('.trash-icon').tooltip({
      title: "Delete quiz"
    });
  });
</script>

app/views/quizzes/invite.html.erb
<div class="row"> 
  <div class="span10 offset1">
    <form action="/quizzes/mail_invite" method="post">
      <%= token_tag nil %>
      <h2>Invite students to add a question to "<%= @quiz.name %>"</h2>
      <% org_users = @users.select do |user| %>
        <% user if user.organization_id == @current_org.id %>
      <% end %>
      <fieldset>
        <input type="hidden" name="quiz_id" value="<%= @quiz.id %>" />
        <input type="checkbox" id="check_all" class="regular-checkbox invite-all" /> Select All
        <br />
        <br />
        <div class="email_users_list">
          <% org_users.in_groups_of(10, false).each do |group| %>
              <div class="span3">
              <ul>
            <% group.each do |user| %>
              <li>
                <%= check_box_tag "recipients[]", user.email, false, :class => "regular-checkbox"%>
                <%= user.name %>
              </li>
            <% end %>
              </ul>
              </div>
          <% end %>
        </div>
      </fieldset>
      <br />
      <br />
      <input type="submit" value="Invite" class="btn btn-primary" />
    </form>
  </div> 
</div>

<script type="text/javascript">
  $(function(){
    $("#check_all").click(function() {
      if ($("#check_all").is(':checked'))
      {
        $('.email_users_list input').attr('checked', 'checked');
      } else {
        $('.email_users_list input').removeAttr('checked');
      }
    });
  });
</script>

app/views/quizzes/new.html.erb
<div class="row"> <div class="span10 offset1">

<h1>New Quiz</h1>

<%= render 'form' %>

</div> </div>

app/views/quizzes/record.html.erb
Thank You

app/views/quizzes/score.html.erb
<div class="row"> <div class="span10 offset1">

<h2><%= @quiz.name %></h2>
<div id ="score" >
<%= @user_quiz.num_correct %> / <%= @user_quiz.total_questions %><br />
</div>
<ol>
  <% @quiz.approved_questions.each do |question| %>
    <li>
    <h4><%= question.name %></h4>
    <ol type="a" class="choices">
    <% question.choices.each do |choice| %>
      <li>
        <% if @answers.detect { |answer| answer.choice.id == choice.id } && choice.is_correct %>
          <span class="correct-answer"><%= choice.name %> << Correct answer selected.</span>
        <% elsif @answers.detect { |answer| answer.choice.id == choice.id } %>
          <span class="wrong-answer"><%= choice.name %> << Answer selected.</span>
        <% elsif choice.is_correct %>
          <span class="correct-answer"><%= choice.name %> << Correct answer.</span>
        <% else %>
          <%= choice.name %>
        <% end %>
      </li>
    <% end %>
    </ol>
    </li>
  <% end %>
</ol>
<%= link_to "Back to all Quizzes", quizzes_path %>

</div> </div>

app/views/quizzes/show.html.erb
<div class="row"> <div class="span10 offset1">

<% if current_user.is_admin? %>
  <% if @quiz.is_published %>
    <p class="alert-success alert">This quiz has been published.</p>
  <% else %>
    <% if @quiz.approved_questions.count > 0 %>
      <p class="alert">This quiz has not been published yet.</p>
    <% else %>
      <p class="alert">This quiz has not been published yet. Quizzes must have at least one selected question to be published.</p>
    <% end %>
  <% end %>
<% end %>

<h1> <%= @quiz.name %> </h1>
<div id="admin-quiz" class="well btn-group">
  <%= link_to "Add a Question", new_question_path(:quiz_id => @quiz.id), class: "btn btn-primary" %>
   <!-- redirect to index, while publishing to true  -->
  <% if current_user.is_admin? %>  
    <%= link_to "Invite Students to Collaborate", quiz_invite_path(@quiz.id), :class => "btn btn-inverse" %>
    <% if !@quiz.is_published? %>
      <%= form_for(@quiz) do |f| %>
        <%= f.hidden_field :is_published, :value => "true" %>
        <div class="actions">
          <button class="btn btn-warning" name="commit" type="submit" value="Publish Quiz" >Publish Quiz</button>
        </div>
        <% end %>
    <% else %>
      <%= form_for(@quiz) do |f| %>
        <%= f.hidden_field :is_published, :value => "false" %>
        <div class="actions">
          <button class="btn btn-warning" name="commit" type="submit" value="Deactivate Quiz" >Unpublish Quiz</button>
        </div>
      <% end %>
    <%end%>   
  <% end %>
</div>

<ol class="questions">
  <% @quiz.questions.order('created_at ASC').each do |question| %>
  <li class="selected-<%= question.selected %>">
    <span class="question">
      <span class="author">(<%= question.author.name %>)</span> <%= question.name %>
    </span>
    <span class="admin-question">
      <%if current_user.is_admin?%>  
        <%= form_for question, :remote => true do |q| %>
          <%= q.hidden_field :selected, :value => "true" %>
          <%= q.submit "Select Question", :class => "select-question approve-icon", :id => "test" %>
        <% end %>
    
        <%= form_for question, :remote => true do |q| %>
         <%= q.hidden_field :selected, :value => "false" %>
         <%= q.submit "Deselect Question", :class => "deselect-question reject-icon" %>
          
         <% end %>
      <% end %>
      <% if current_user.is_admin? || current_user.id == question.user_id %>
        <%= link_to "Edit Question", edit_question_path(question), :class => "edit-question edit-icon" %>
      <% end %>
    </span>
    <ol class="choices" type="a">
      <% question.choices.each do |choice| %>
        <%if current_user.is_admin? || question.author == current_user%>
            <%if choice.is_correct%>
              <li class="correct-answer"><%= choice.name %></li>
            <%else%>
             <li><%= choice.name %></li> 
            <% end %> 
        <%else%>   
        <!-- <li><%#= choice.name %></li> -->
        <!-- we don't want students to see choices before actually taking quiz -->
        <% end %>
      <% end %>
    </ol>
  </li>
  <% end %>
</ol>

</div> </div>


<script text="type/javascript">
  $(function() {
    $('.selected-true .select-question').hide();
    $('.selected-false .deselect-question').hide();

    $('.select-question').click(function(){
      $(this).parent().siblings('form').children('.deselect-question').show();
      $(this).parents().eq(2).removeClass("selected-false");
      $(this).parents().eq(2).addClass("selected-true");
      $(this).hide();
    });

    $('.deselect-question').click(function(){
      $(this).parent().siblings('form').children('.select-question').show();
      $(this).parents().eq(2).removeClass("selected-true");
      $(this).parents().eq(2).addClass("selected-false");
      $(this).hide();
    });

    $('.edit-icon').tooltip({
      title: "Edit question"
    });
    $('.approve-icon').tooltip({
      title: "Approve this question"
    });
    $('.reject-icon').tooltip({
      title: "Reject this question"
    });
  });
</script>

app/views/quizzes/user_quiz_history.html.erb
<div class="row"> <div class="span10 offset1">

<h1>Quizzes they have taken:</h1>


<% @user = User.find_by_id(user.id) %>
<%if @quizzes.count > 0 %>

    <% @quizzes.each do |quiz|  %>
      <% if current_user.has_taken?(quiz) %>
      <% @num_correct = QuizGrader.num_correct(current_user.answers_for_quiz(quiz.id), quiz)%>
      <div class="quiz_listing">
        <% if @num_correct.to_f/quiz.approved_questions.count >= quiz.passing_grade.to_f/100 %>
          <% image_source = "/assets/smile_1.png" %>
        <% else %>
          <% image_source = "/assets/smile_5.png" %>
        <% end %>
        
        <h3><%= quiz.name %> <img src=<%= image_source %> ></h3>

        <div class="quiz_info">
          <p class="quiz_description"><%= quiz.description %></p>
          Taken <%= time_ago_in_words(quiz.answers.find_by_quiz_id(quiz).created_at) %> ago.
          <%= link_to "View result", score_path(quiz.id) %>
        </div>

      </div>

      <% end %>
    <% end %>

<% else %>

  You have not taken any quizzes. Visit the <%= link_to "Take Quiz page", quizzes_path %> to take one.

<% end %>

</div> </div>