config/routes.rb
OpenExam::Application.routes.draw do
  
  get "homepage/index"

  get '', to: 'quizzes#index', constraints: lambda {|r| r.subdomain.present? && r.subdomain != 'www'}

  get "about", to: 'info#about'
  get "privacy", to: 'info#privacy', as: 'privacy'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/quiz/:quiz_id' => 'admin#quiz', as: 'quiz_stats'

  get "sessions/new"

  get 'quizzes/:id/score/:user_id' => 'quizzes#score', as: 'score'

  get 'quizzes/:id/invite' => 'quizzes#invite', as: 'quiz_invite'
  post 'quizzes/mail_invite' => 'quizzes#mail_invite'
  
  get 'quizzes/collaborate' => 'quizzes#collaborate', as: 'quiz_collaborate'

  get 'users/invite' => 'users#invite', as: 'invite_users'
  post 'users/create_students' => 'users#create_students'

  get 'organizations/demo' => 'organizations#demo'

  resources :organizations

  resources :quizzes

  resources :users

  resources :sessions

  resources :questions do
    resources :answers, :controller => 'questions/answers'
  end

  root :to => 'homepage#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/views/admin/index.html.erb
<div class="row">
<div class="span12">
  <div class="well">
  <div class="btn-group">
    <%= link_to 'Invite a Member', invite_users_path, :class => "btn btn-primary" %>
    <%= link_to 'Create a Quiz', new_quiz_path, :class => "btn btn-success" %>
    <%= link_to "Edit Organization", edit_organization_path(@current_org.id), :class => "btn btn-warning"%>
  </div>
  </div>
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#tab1" data-toggle="tab">Members</a> 
    </li>
    <li>
      <a href="#tab2" data-toggle="tab"> Quizzes </a>
    </li>
  </ul>
  <div id="admin-content" class="tab-content">
    <div class="tab-pane active" id="tab1">
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>
          <th>Edit</th>
          <th>Delete</th>
          <th>Quiz History</th>
        </tr>

      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure you want to delete #{user.name}? \nThis cannot be undone!".html_safe } %></td>
          <td><%= link_to 'Quiz History', user_path(:id => user.id) %></td>
          <td>
            <% if current_user.is_admin? && !user.is_admin? %>
              <%= form_for(user) do |f| %>
                <%= f.hidden_field :role, :value => "Admin" %>
                  <button class="btn btn-mini" name="commit" type="submit" onclick="return confirm('Are you sure you want to make this user an admin?');">Make Admin</button>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </table>

      <br />
    </div>

    <div class="tab-pane" id="tab2">
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Published?</th>
          <th>Students Taken</th>
          <th> Class Average </th>
          <th> Stats </th>
        </tr>

      <% @quizzes.each do |quiz| %>
        <tr>
          <td><%= quiz.name%> </td>
          <td><%= quiz.description %></td>
          <td><%= "Yes" if quiz.is_published %> <%= "No" if !quiz.is_published %></td>
          <% taken_quizzes = quiz.user_quizzes %>
          <% users_who_took_quiz = taken_quizzes.collect {|n| n.user_id} %>
          <% each_user = users_who_took_quiz.map do |id|%>
            <% User.find_by_id_and_role(id, "Admin") %>
          <% end %>
          <% each_user.compact! %>

          <td><%= taken_quizzes.count %> / <%= (@current_org.users.where(:role => "Student").all.count) + each_user.count %></td>
          <td><%= QuizGrader.percent_correct(quiz)%></td>
          <% if UserQuiz.find_by_quiz_id(quiz.id) %>
            <td><%= link_to "View Stats", quiz_stats_path(quiz.id) %></td>
          <% else %>
            <td>No available stats</td>
          <% end %>
          
        </tr>
      <% end %>
      </table>

      <br />
    </div>
  </div>
</div>
</div>
</div>

app/views/admin/quiz.html.erb
<h2><em><%= @quiz.name %></em> Quiz</h2>

<div class="row">
<div class="span12">
  <div id="quiz_chart" style="width: 560px; height: 300px;"></div>
  

<% scores_top = QuizGrader.student_correct_percent_by_quiz(@quiz) %>
<% count = Hash.new(0) %>
<% scores_top.each {|v| count[v]+=1} %>


<script type="text/javascript" charset="utf-8">
    $(function () {
    new Highcharts.Chart({
      chart: { renderTo: 'quiz_chart',
               type: 'column'  
      },
      credits: { enabled:false },
      title: { text: 'Quiz Distribution' },
      xAxis: { 
               min: 0,
               max: 100,
        title: { text: 'Percent Correct'}
      },
      plotOptions: {
        series: {
          pointWidth: 15
        }      
      },

      yAxis: {
        allowDecimals: false,
        title: { text: 'Number of Students'}


      },
      series: [{
        name: 'Students',
        showInLegend: false,
        data: <%= count.to_a.inspect %>

      }]
    });
  });
  </script>


  <div class="stats_highlights" style="padding: 20px;">
    Average Score: 
    <%= (QuizGrader.average_quiz_score(@quiz).to_f.round(2)/@quiz.questions.count * 100).round(2) %>%
    <br />
    Highest Score:
    <%= (QuizGrader.highest_quiz_score(@quiz).to_f/@quiz.questions.count * 100).round(2) %>%
    <br />
    Lowest Score:
    <%= (QuizGrader.lowest_quiz_score(@quiz).to_f/@quiz.questions.count * 100).round(2) %>%
    <br />
    Hardest Question:
    "<%= QuizGrader.hardest_question(@quiz) %>"
    authored by
    <%= QuizGrader.hardest_question_author(@quiz) %>
    <br />
    Best score:
    <%= QuizGrader.most_correct_answers(@quiz) %>
    answered 
    <%= QuizGrader.correct_responses(@quiz) %>  out of  <%= @quiz.questions.count%> questions correctly.
    <br />
  </div>
<br />
<div class="span7">
<h1>Question Breakdown:</h1>
<% QuizGrader.question_score_counts(@quiz).each do |question, value| %>
    <h2 style="padding-top:20px;">Question #<%= question.position %>: <%= question.name %></h2>

  <div id="question_chart_<%= question.position %>" style="width: 480px; height: 300px;margin-left:30px;"></div>

<script type="text/javascript" charset="utf-8">
    $(function () {
    new Highcharts.Chart({
      chart: { renderTo: 'question_chart_<%= question.position %>',
               plotBackgroundColor: null,
               plotBorderWidth: null,
               plotShadow: false
      },
      credits: { enabled:false },
      title: { text: '' },
      xAxis: { 
               min: 0,
               max: 100
               
      },
      plotOptions: {
        pie: {
          size: 190,
          dataLabels: {
                        enabled: false
                    },
          showInLegend: true
        },  
        series: {
          pointWidth: 15
        }      
      },

      yAxis: {
        title: { text: 'Number of Students'},

      },
      series: [{
        type: 'pie',
        name: 'Number of students selected',
        data: [

          <% question.choices.each do |choice| %>
            <% if choice.is_correct == true%>
              {
                name: "<%= escape_for_js(choice.name) %> (Correct)",
                y: <%= QuizGrader.num_answers_for_choice(choice.id) %>,
                sliced: true,
                selected: true
              },
            <% else %>
                ["<%= escape_for_js(choice.name) %>",<%= QuizGrader.num_answers_for_choice(choice.id) %>],
            <% end %>
          <% end %>

        ]

      }]
    });
  });
  </script>
  
  <p style="margin-left:30px;"><%= value %> out of <%= pluralize(QuizGrader.num_answers_for_question(question.id), 'student') %> answered this question correctly.
  </p>

<% end %>
</div>

<div class="span4 pull-right">

<h4 style="text-align:center;">Taken:</h4>
  <table class="table" >
        <tr>
          <th style="text-align:right;">Name</th>
        </tr>
        
    <% @quiz.completed.each do |user_quiz| %>
   
        <tr>
          <td style="text-align:right;"><%= (User.find_by_id(user_quiz.user_id)).name %></td>
        </tr>    
    <% end %>      

  </table>
<h4 style="text-align:center;">In Progress:</h4>
  <table class="table" >
        <tr>
          <th style="text-align:right;">Name</th>
        </tr>
        
    <% @quiz.in_progress.each do |user_quiz| %>
   
        <tr>
          <td style="text-align:right;"><%= (User.find_by_id(user_quiz.user_id)).name %></td>
        </tr>    
    <% end %>

    <% if @quiz.in_progress.empty? %>
      <tr>
          <td style="text-align:right;">( None )</td>
        </tr>    
    <% end %>
  </table> 

  <% taken_user_quizzes = UserQuiz.find_all_by_quiz_id(@quiz.id) %>
  <% taken_user_ids = taken_user_quizzes.map { |x| x.user_id } %>
  <% taken_user_names = taken_user_ids.map { |x| User.find_by_id(x) } %>

  
  <% yetto = (User.find_all_by_organization_id(@current_org.id)) - taken_user_names %>





<h4 style="text-align:center;">Not Taken:</h4>
  <table class="table" >
        <tr>
          <th style="text-align:right;">Name</th>
        </tr>
        <tr>
            <% yetto.each do |n| %>
            <td style="text-align:right;"><%= n.name %></td>
        </tr>   
        <% end %> 
       
  </table>  
</div> 
<div class="clearfix"></div>
</div>
</div>

app/views/admin/show.html.erb
<div class="row">
<div class="span12">

<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

</div>
</div>