config/routes.rb
OpenExam::Application.routes.draw do
  
  get "homepage/index"

  get '', to: 'quizzes#index', constraints: lambda {|r| r.subdomain.present? && r.subdomain != 'www'}

  get "about", to: 'info#about'
  get "privacy", to: 'info#privacy', as: 'privacy'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/quiz/:quiz_id' => 'admin#quiz', as: 'quiz_stats'

  get "sessions/new"

  get 'quizzes/:id/score/:user_id' => 'quizzes#score', as: 'score'

  get 'quizzes/:id/invite' => 'quizzes#invite', as: 'quiz_invite'
  post 'quizzes/mail_invite' => 'quizzes#mail_invite'
  
  get 'quizzes/collaborate' => 'quizzes#collaborate', as: 'quiz_collaborate'

  get 'users/invite' => 'users#invite', as: 'invite_users'
  post 'users/create_students' => 'users#create_students'

  get 'organizations/demo' => 'organizations#demo'

  resources :organizations

  resources :quizzes

  resources :users

  resources :sessions

  resources :questions do
    resources :answers, :controller => 'questions/answers'
  end

  root :to => 'homepage#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  subdomain   :string(255)
#  invite_code :string(255)
#

class Organization < ActiveRecord::Base
  attr_accessible :name, :subdomain, :invite_code

  validates :name, :presence => :true, :length => { :maximum => 75 }

  has_many :users
  has_many :quizzes

  accepts_nested_attributes_for :users
  validate :validate_unique_users

  def validate_unique_users
    validate_uniqueness_of_in_memory(users, [:email, :organization_id], 'User e-mails must be unique.')
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :organizations_only, :except => [:new, :create, :demo]
  before_filter :authorize, :only => [:show ]
  before_filter :authorize_admin_or_superuser, :only => [:edit]
  before_filter :authorize_superuser, :only => [ :index, :update, :destroy]
  before_filter :no_new_org, :only => [:new]
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find_by_subdomain!(request.subdomain)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new@
  # GET /organizations/new.json
  def new 
    @user = User.new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create

    @organization = Organization.new(params.fetch(:organization))
    @user = @organization.users.build(params.fetch(:user).merge({:role => "Admin"}))

    respond_to do |format|
      if @organization.save
        OpenExamMailer.registration_confirmation(@user).deliver
        session[:user_id] = @user.id
        format.html { redirect_to admin_url(:subdomain => @organization.subdomain), notice: "Your organization has been created. Make sure to access your organization at #{@organization.subdomain}.openexam.org" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def demo
    increment = User.count + 1

    org = Organization.find_by_subdomain("demo")
    demo_user = User.new(
      name: "Flatiron Guest",
      email: "flatiron#{increment}@flatironschool.com",
      organization_id: org.id,
      password: "asdf",
      password_confirmation: "asdf",
      role: "Student"
      )

    if demo_user.save
      session[:user_id] = demo_user.id
      redirect_to root_url(:subdomain => "demo"), notice: "Welcome to the demo! You're logged in as a student. Take a quiz or add questions to unpublished quizzes."
    else
      redirect_to root_path
    end

  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private

  def no_new_org
    if current_org && current_user && !current_user.is_superuser?
      redirect_to user_path(current_user.id) 
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>

<% if @organization.errors.any? %>
  <div class="row">
  <div class="offset1 span8">
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  </div>
<% end %>

<div class="row">
  <div class="offset span4">

    <h3>Your Info:</h3>

    <%= fields_for @user do |user_f| %>

      <div class="field">
        <%= user_f.label :name %>
        <%= user_f.text_field :name %>
      </div>
      <div class="field">
        <%= user_f.label :email %>
        <%= user_f.text_field :email %>
      </div>
      <div class="field">
        <%= user_f.label :password %>
        <%= user_f.password_field :password %>
      </div>
      <div class="field">
        <%= user_f.label :password_confirmation %>
        <%= user_f.password_field :password_confirmation %>
      </div>

    <% end %>
  </div>

  <div class="offset1 span5">

    <h3>Organization:</h3>

    <div class="field">
      <%= f.label "Organization Name" %>
      <%= f.text_field :name, :placeholder => "School" %>
    </div>
    <div class="field">
      <%= f.label :subdomain %>
      <%= f.text_field :subdomain, :placeholder => "subdomain.openexam.org"%>
    </div>
    <div class="field">
      <%= f.label :invite_code %>
      <%= f.text_field :invite_code, :placeholder => "private code for new users" %>
    </div>
    
    <br/>
    <div class="controls offset5" style="margin-top: 8px;">
      <input name="commit" class = "btn btn-primary" type="submit" value="Sign up">
    </div>

  </div>
</div>

<% end %>

app/views/organizations/edit.html.erb
<h1>Edit your Organization</h1>
<br />
<%= form_for(@organization) do |f| %>
  
<% if @organization.errors.any? %>
  <div class="row"> 
  <div class="span10 offset1">

    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>


    </div>
  </div>
  <% end %>

<div class="row"> 
  <div class="span10 offset1">

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
<% if current_user.is_superuser? %>  
    <div class="field">
     <%= f.label :subdomain %>
     <%= f.text_field :subdomain %>
   </div>
<% end %> 
    <div class="field">
      <%= f.label :invite_code %>
      <%= f.text_field :invite_code %>
    </div>
  <% end %>

  <div class="controls">   
   <input name="commit" class = "btn btn-primary" type="submit" value="Submit">

  </div>

<br/><br/>
  <% if current_user.is_superuser? %>
    <%= link_to 'Back', organizations_path %>
  <% elsif current_user.is_admin? %>
    <%= link_to 'Back', admin_path %>
  <% end %>

</div>
</div>

app/views/organizations/index.html.erb
<div class="row">
  <div class="offset1 span10">

    <h1>Listing organizations</h1>

    <table class="table">
      <tr>
        <th>Name</th>
        <th>Subdomain</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>

    <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to organization.name, root_url(:subdomain => organization.subdomain) %></td>
        <td><%= organization.subdomain %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <% unless organization.name == "Admin" %>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </table>

    <p>
      <%= link_to 'New Organization', new_organization_path, :class => "btn btn-primary" %>
    </p>

  </div>
</div>

app/views/organizations/new.html.erb
<h1>Sign up your organization</h1>

<div class="row">
  <div class="offset1 span10">

  <%= render 'form' %>

  </div>
</div>

app/views/organizations/show.html.erb
<div class="row"> 
  <div class="span10 offset1">

    <p id="notice"><% notice %></p>


    <h2><%= @organization.name %></h2>

    <%= link_to "Quizzes", quizzes_path(:subdomain => @organization.subdomain) %>

    <%= link_to 'Edit', edit_organization_path(@organization) %> |
    <%= link_to 'Back', organizations_path %>

</div>
</div>