config/routes.rb
OpenExam::Application.routes.draw do
  
  get "homepage/index"

  get '', to: 'quizzes#index', constraints: lambda {|r| r.subdomain.present? && r.subdomain != 'www'}

  get "about", to: 'info#about'
  get "privacy", to: 'info#privacy', as: 'privacy'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/quiz/:quiz_id' => 'admin#quiz', as: 'quiz_stats'

  get "sessions/new"

  get 'quizzes/:id/score/:user_id' => 'quizzes#score', as: 'score'

  get 'quizzes/:id/invite' => 'quizzes#invite', as: 'quiz_invite'
  post 'quizzes/mail_invite' => 'quizzes#mail_invite'
  
  get 'quizzes/collaborate' => 'quizzes#collaborate', as: 'quiz_collaborate'

  get 'users/invite' => 'users#invite', as: 'invite_users'
  post 'users/create_students' => 'users#create_students'

  get 'organizations/demo' => 'organizations#demo'

  resources :organizations

  resources :quizzes

  resources :users

  resources :sessions

  resources :questions do
    resources :answers, :controller => 'questions/answers'
  end

  root :to => 'homepage#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/views/layouts/_flash_messages.html.erb
<p>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenExam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <% if current_org %>
            <%= link_to current_org.name, root_path, :class => 'brand' %>
          <% else %>
            <%= link_to "Open Exam", root_path, :class => 'brand' %>
          <% end %>

          <div class="nav-collapse collapse">
            
            <ul class="nav">
              <% if current_org %>
                <% if controller?("quizzes") && action?("index") %>
                  <li class="active">
                <% else %>
                  <li>
                <% end %>
                
                <%= link_to "Take Quiz", quizzes_path %></li>

                <% if controller?("quizzes") && action?("collaborate") %>
                  <li class="active">
                <% else %>
                  <li>
                <% end %>

                <%= link_to "Collaborate", quiz_collaborate_path %></li>
              <% end %>
            </ul>

            <ul class="nav pull-right">
              <% if current_org %>
                <% if current_user && current_user.is_admin? %>

                  <% if controller?("admin") %>
                    <li class="active">
                  <% else %>
                    <li>
                  <% end %>
                    <%= link_to "Admin", admin_path %>
                  </li>
                <% end %>

                <% if current_user && current_user.is_superuser? %>
                  <li>
                    <%= link_to "Organizations", organizations_path %>
                  </li>
                <% end %>

                <% if current_user %>

                  <li>
                    <a href="<%= user_path(current_user) %>"><img src="<%= "http://gravatar.com/avatar/#{current_user.gravatar_hash}?s=25" %>" class="user_nav_photo" /> <%= current_user.name %></a>
                  </li>

                  <li>
                    <%= link_to "Log Out", logout_path %>
                  </li>              
                <% else %>
                  <li>
                    <%= link_to "Log In", login_path %>
                  </li>
                <% end %>


              <% end %>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container content-wrap row-fluid">
      <div class="fluid-wrap">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    </div>
    
    <footer class="container content-wrap">
      <a href="http://www.openexam.org"><strong>Open Exam</strong></a> 2012 &nbsp; 
      <%= link_to_unless_current "About", about_path %> | 
      <%= link_to_unless_current "Privacy", privacy_path %> | 
      <a href="http://students.flatironschool.com/">Contact</a>

      <% if Rails.env.development? %>
        <div id="dev-tools" style="border:2px solid #eee;margin-top:30px;text-align:center;">
            <strong>DEV</strong> <%= params %>
        </div>
      <% end %>

    </footer>

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33578770-6']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</body>
</html>